version: "3.8"
services:
  app:
    container_name: salmon_stats_app
    build:
      context: ./app
    ports:
      - 5000:5000
    networks:
      - salmon_stats_network

networks:
  salmon_stats_network:
    external: false
