version: "3.8"
services:
  db:
    image: postgres:14.2
    container_name: salmon_stats_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    networks:
      - salmon_stats_network

networks:
  salmon_stats_network:
    external: false
