openapi: 3.0.0
paths:
  /v1/users:
    get:
      operationId: UsersController_findMany
      parameters:
        - name: offset
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
      responses:
        '200':
          description: ''
  /v1/users/{user_id}:
    get:
      operationId: UsersController_find
      parameters:
        - name: nsaid
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
        '404':
          description: ''
  /v1/results/{salmon_id}:
    get:
      operationId: 取得
      summary: ''
      parameters:
        - name: salmon_id
          required: true
          in: path
          description: リザルトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
      tags:
        - リザルト
    put:
      operationId: 更新
      summary: ''
      parameters:
        - name: salmon_id
          required: true
          in: path
          description: リザルトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
      tags:
        - リザルト
    delete:
      operationId: 削除
      summary: ''
      parameters:
        - name: salmon_id
          required: true
          in: path
          description: リザルトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
      tags:
        - リザルト
  /v1/results:
    get:
      operationId: 一括取得
      summary: ''
      parameters:
        - name: offset
          required: true
          in: query
          schema:
            minimum: 0
            title: offset
            default: 0
            type: number
        - name: limit
          required: true
          in: query
          schema:
            minimum: 0
            maximum: 200
            title: limit
            default: 25
            type: number
        - name: is_clear
          required: false
          in: query
          description: クリアしたリザルトのみ
          schema:
            title: ''
            default: false
            type: boolean
        - name: nsaid
          required: false
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - リザルト
    post:
      operationId: 登録
      summary: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - リザルト
  /v1/results/schedules/{schedule_id}:
    get:
      operationId: スケジュール指定
      summary: ''
      parameters:
        - name: offset
          required: true
          in: query
          schema:
            minimum: 0
            title: offset
            default: 0
            type: number
        - name: limit
          required: true
          in: query
          schema:
            minimum: 0
            maximum: 200
            title: limit
            default: 25
            type: number
        - name: is_clear
          required: false
          in: query
          description: クリアしたリザルトのみ
          schema:
            title: ''
            default: false
            type: boolean
        - name: nsaid
          required: false
          in: query
          schema:
            type: string
        - name: schedule_id
          required: true
          in: path
          description: シフトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
      tags:
        - リザルト一覧
  /v1/results/users/{nsaid}:
    get:
      operationId: プレイヤー指定
      summary: ''
      parameters:
        - name: nsaid
          required: true
          in: path
          schema:
            type: string
        - name: offset
          required: true
          in: query
          schema:
            minimum: 0
            title: offset
            default: 0
            type: number
        - name: limit
          required: true
          in: query
          schema:
            minimum: 0
            maximum: 200
            title: limit
            default: 25
            type: number
      responses:
        '200':
          description: ''
      tags:
        - リザルト一覧
  /v1/ranking/schedules/{schedule_id}:
    get:
      operationId: 取得
      summary: ''
      parameters:
        - name: schedule_id
          required: true
          in: path
          description: シフトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
      tags:
        - ランキング
  /v1/schedules/{schedule_id}/stats:
    get:
      operationId: 統計取得
      summary: ''
      parameters:
        - name: schedule_id
          required: true
          in: path
          description: シフトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
      tags:
        - スケジュール
  /v1/schedules:
    get:
      operationId: 取得
      summary: ''
      description: スケジュールを取得します
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - スケジュール
    post:
      operationId: 追加
      summary: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - スケジュール
info:
  title: Salmon Stats API Documents
  description: ''
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    PaginatedDto:
      type: object
      properties:
        total:
          type: integer
          description: 総数
        limit:
          type: integer
          description: 取得数
        offset:
          type: integer
          description: オフセット
      required:
        - total
        - limit
        - offset
